ДЗ 1
marysss/2020-1-Atom-QA-Python-M-Goncharova pull request #1
Opened 2020-03-11 09:18 UTC by marysss

Домашнее задание №1

Прошу @snicks92 или @z1ll1 проверить его.

Что было сделано:
1. Подготовлено рабочее окружения для разработки автоматических тестов. 
2. Написано по 5 автотестов с учетом техник тест-дизайна на каждую из структур данных в Python: List, Set, Dictionary, String, Int. (Все тесты для разных структур вынесены в отдельные файлы)
3. Как минимум один тест на каждую структуру параметризован.
4. Как минимум один тест на каждую структуру находится в классе. 
5. Проверить стиль кода линтером pylint 7,71/10

2020-03-12 14:44 UTC, sniiick requested changes
Мелкие замечания

2020-03-12 14:44 UTC, snicks92 commented on test_dict.py
> +    assert dct == {"a": "a",
1. sorted не сортирует исходный список.
2. assert вернет True независимо от порядка, он проверяет только значения
```python
>>> {2: 2, 1: 1} == {1: 1, 2: 2}
True
```

2020-03-12 14:44 UTC, snicks92 commented on test_int.py
> +    assert int(a) == a//1
Не хватает пустой строки в конце файла

2020-03-23 16:04 UTC, marysss commented
Извините, что я не исправила мелкие замечания сразу.

Был исправлен тест на sorted в файле test_dist.py и добавлена последняя строка в файле test_int.py.

Заметила. что у меня совсем нет баллов в успеваемости, это связано с тем, что не были исправлены замечания? Если вы помните я сделала задание по первому дедлайну, но вы мне сказали исправить PR и бранч, потому что было много лишних файлов, поэтому я перезаливала их позже.

2020-03-23 18:31 UTC, sniiick approved these changes
ОК

2020-03-23 18:31 UTC, merged

2020-03-23 18:32 UTC, snicks92 commented
> Извините, что я не исправила мелкие замечания сразу.
> 
> Был исправлен тест на sorted в файле test_dist.py и добавлена последняя строка в файле test_int.py.
> 
> Заметила. что у меня совсем нет баллов в успеваемости, это связано с тем, что не были исправлены замечания? Если вы помните я сделала задание по первому дедлайну, но вы мне сказали исправить PR и бранч, потому что было много лишних файлов, поэтому я перезаливала их позже.

Баллов нет потому что первая и единственная домашка еще не была зачтена. Сейчас я ее зачел, вмержил ПР и проставил баллы. Теперь есть =)

2020-03-23 18:33 UTC, marysss commented
Супер, спасибо большое!